# Generated by Django 2.2.1 on 2019-06-15 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shareland.commons


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=100, verbose_name='Post heading')),
                ('post_text', models.TextField(default='', verbose_name='Post text')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Creation date & time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.PositiveSmallIntegerField(choices=[(1, 'ok-hand'), (2, 'expressionless-face'), (3, 'sparkling-heart'), (4, 'rolling-on-floor-laughing'), (5, 'face-with-open-mouth'), (6, 'crying-face'), (7, 'pouting-face')], verbose_name='Reaction')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postreactions', to='post.Post')),
                ('reactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shareland.commons.get_path, verbose_name='Image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postimages', to='post.Post')),
            ],
            options={
                'verbose_name': 'Post related image',
                'verbose_name_plural': 'Post related images',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True, null=True, verbose_name='Textual comment')),
                ('comment_image', models.ImageField(blank=True, null=True, upload_to=shareland.commons.get_path, verbose_name='Image comment')),
                ('comment_created', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Commented at')),
                ('Commentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Commentor', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post.Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.Post')),
            ],
        ),
    ]
