# Generated by Django 2.2.1 on 2019-06-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_created']},
        ),
    ]
