# Generated by Django 2.2.1 on 2019-06-15 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shareland.commons


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Following'), (2, 'Blocked')], verbose_name='Relationship status')),
            ],
            options={
                'verbose_name': 'Following',
                'verbose_name_plural': 'Following',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=20, verbose_name="User's timezone")),
                ('avatar', models.ImageField(default='default_avatar.png', upload_to=shareland.commons.get_path, verbose_name='Change avatar')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', through='userprofile.Relationship', to='userprofile.UserProfile')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile data',
                'verbose_name_plural': 'Profile data',
            },
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='userprofile.UserProfile'),
        ),
    ]
