# Generated by Django 2.2.1 on 2019-06-02 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=20, verbose_name="User's timezone")),
                ('avatar', models.ImageField(default='default_avatar.png', upload_to=userprofile.models.get_path, verbose_name='Change avatar')),
                ('joined', models.DateTimeField(auto_now_add=True, verbose_name='Joined')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='userprofile.UserProfile')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile data',
                'verbose_name_plural': 'Profile data',
            },
        ),
    ]
